name: algebraic_types
description: Dart macros for algebraic types
version: 0.0.3
repository: https://github.com/mcmah309/algebraic_types

environment:
  sdk: ^3.5.1

dependencies:
  macros: ^0.1.2-main.4
  json: ^0.20.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
