name: dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-232.0.dev

dependencies:
  http: ^1.2.2
  json: ^0.20.0
  algebraic_types:
    path: ../..

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
